client_id = "961772163d178943fdf64612cc0f6a5d"

[app]
name = "Nudio (Product Studio)"
application_url = "https://app.nudio.ai/shopify/app"
embedded = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = ["customers/data_request"]
uri = "https://app.nudio.ai/shopify/webhooks/customers/data_request"

[[webhooks.subscriptions]]
topics = ["customers/redact"]
uri = "https://app.nudio.ai/shopify/webhooks/customers/redact"

[[webhooks.subscriptions]]
topics = ["shop/redact"]
uri = "https://app.nudio.ai/shopify/webhooks/shop/redact"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "https://app.nudio.ai/shopify/webhooks/app/uninstalled"
