name = "Nudio (Product Studio)"
handle = "nudio-product-studio"
client_id = "961772163d178943fdf64612cc0f6a5d"
application_url = "https://app.nudio.ai/shopify/app"
embedded = true

[auth]
redirect_urls = ["https://app.nudio.ai/shopify/oauth/callback"]

[access_scopes]
scopes = "read_products,write_products"

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://app.nudio.ai/shopify/webhooks/compliance"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "https://app.nudio.ai/shopify/webhooks/app/uninstalled"
