[app]
name = "Nudio (Product Studio)"
application_url = "https://app.nudio.ai/shopify/app"
embedded = true

[webhooks]
api_version = "2025-10"

[[webhooks.subscriptions]]
topics = ["customers/data_request"]
uri = "https://app.nudio.ai/shopify/webhooks/customers/data_request"

[[webhooks.subscriptions]]
topics = ["customers/redact"]
uri = "https://app.nudio.ai/shopify/webhooks/customers/redact"

[[webhooks.subscriptions]]
topics = ["shop/redact"]
uri = "https://app.nudio.ai/shopify/webhooks/shop/redact"
